const CardData = [
  {
    id: 1,
    image: "/pictures/Sirubari.jpeg",
    location: "Sirubari",
    name: "Sirubari Homestay",
    rooms: " 12 rooms",
    price: "From Nrs 1200/night ",
  },

  {
    id: 2,
    image: "/pictures/Ashish-aama.jpeg",
    location: "Ghandruk",
    name: "Ashish Aama Homestay",
    rooms: " 8 rooms",
    price: " From Nrs 1000/night",
  },

  {
    id: 3,
    image: "/pictures/barahi.jpeg",
    location: "Ghorepani",
    name: "Barahi Ghorepani Homestay",
    rooms: "8 rooms ",
    price: "From Nrs 1700/night ",
  },
  {
    id: 4,
    image: "/pictures/my-beautiful.jpeg",
    location: "Kaski",
    name: "My Beautiful Cottage",
    rooms: "10 rooms ",
    price: "From Nrs 1000/night ",
  },
  {
    id: 5,
    image: "/pictures/heaven.jpeg",
    location: "Dhampus",
    name: "Heaven Homestay",
    rooms: " 6 rooms",
    price: " From Nrs 2500/night",
  },
  {
    id: 6,
    image: "/pictures/machhapuchhre.jpeg",
    location: "Kaski",
    name: "Machhapuchhre Homestay",
    rooms: " 18 rooms",
    price: "From Nrs 1500/night ",
  },
  {
    id: 7,
    image: "/pictures/dhampus.jpeg",
    location: "Dhampus",
    name: "Dhampus Holiday Homestay",
    rooms: "11 rooms ",
    price: "From Nrs 1400/night ",
  },
  {
    id: 8,
    image: "/pictures/se-sauba.jpeg",
    location: "Sikles",
    name: "Se Sauba Homestay",
    rooms: " 10 rooms",
    price: "From Nrs 1500/night ",
  },
  {
    id: 9,
    image: "/pictures/purnima homestay.jpeg",
    location: "Sikles",
    name: "Sikless Purnima Homestay",
    rooms: " 10 rooms",
    price: "From Nrs 1500/night ",
  },
  {
    id: 10,
    image: "/pictures/ayusha.jpeg",
    location: "Ghorepani",
    name: "Aayusha Homestay",
    rooms: "6 rooms ",
    price: " From Nrs 2000/night",
  },
  {
    id: 11,
    image: "/pictures/newarni-dd.jpeg",
    location: "Bandipur",
    name: "Newarni dd ko Homestay",
    rooms: "15 rooms ",
    price: "From Nrs 1500/night ",
  },
  {
    id: 12,
    image: "/pictures/samira.jpeg",
    location: "Bandipur",
    name: "Bandipur Samira Homestay",
    rooms: "8 rooms ",
    price: "From Nrs 1700/night ",
  },
];

export default CardData;
